//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevAlternatives.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string FisicalAddress1 { get; set; }
        public string FisicalAddress2 { get; set; }
        public string FisicalCity { get; set; }
        public string FisicalZip { get; set; }
        public string FisicalState { get; set; }
        public string PostalAddress1 { get; set; }
        public string PostalAddress2 { get; set; }
        public string PostalCity { get; set; }
        public string PostalZip { get; set; }
        public string PostalState { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string WebAddress1 { get; set; }
        public string WebAddress2 { get; set; }
        public string IsActive { get; set; }
    }
}
