//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevAlternatives.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactsLead
    {
        public int ContactsLeadsID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public string Company { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string E_mail_Address { get; set; }
        public string Job_Title { get; set; }
        public string Business_Phone { get; set; }
        public string Home_Phone { get; set; }
        public string Mobile_Phone { get; set; }
        public string Fax_Number { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State_Province { get; set; }
        public string ZIP_Postal_Code { get; set; }
        public string Country_Region { get; set; }
        public string Web_Page { get; set; }
        public string Notes { get; set; }
        public byte[] Attachments { get; set; }
        public string Category { get; set; }
    }
}
