//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevAlternatives.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int id { get; set; }
        public string citycode { get; set; }
        public string name { get; set; }
        public string printable_name { get; set; }
        public string iso3 { get; set; }
        public Nullable<short> numcode { get; set; }
    }
}
