//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevAlternatives.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FisicalAddress1 { get; set; }
        public string FisicalAddress2 { get; set; }
        public string FisicalCity { get; set; }
        public string FisicalZip { get; set; }
        public string FisicalState { get; set; }
        public string PostalAddress1 { get; set; }
        public string PostalAddress2 { get; set; }
        public string PostalCity { get; set; }
        public string PostalZip { get; set; }
        public string PostalState { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string WorkPhone { get; set; }
        public Nullable<System.DateTime> CustomerStartDate { get; set; }
        public string CustomerActive { get; set; }
        public Nullable<System.DateTime> CustomerLastVisitDate { get; set; }
    }
}
