//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevAlternatives.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskManagement
    {
        public int TaskID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> ContactsLeadsID { get; set; }
        public string Tittle { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public string Completed { get; set; }
        public string AssignedTO { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public byte[] Attached { get; set; }
    }
}
