//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevAlternatives.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskManagementFilter
    {
        public int TaskManagementFilterID { get; set; }
        public string ObjectType { get; set; }
        public string ObjectName { get; set; }
        public string FilterName { get; set; }
        public string FilterString { get; set; }
        public string SortString { get; set; }
        public string Default { get; set; }
        public string Description { get; set; }
    }
}
